name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Run this workflow when a tag matching the pattern is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4.2.1

    - name: Set up Boost dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev
    - name: Install CMake
      run: |
        sudo apt-get install -y cmake
    - name: Configure CMake project
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: Build project
      run: |
        cd build
        make
    - name: Create release binary
      run: |
        mkdir -p release
        cp build/mce_encryption_server_cpp release/
    
    - name: Upload binary to release
      uses: actions/upload-artifact@v4.4.2
      with:
        name: release-binary
        path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download binary
      uses: actions/download-artifact@v4.1.8
      with:
        name: release-binary
        path: ./release/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: ./release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}